// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatillaDash.Infrastructure.Persistence;

#nullable disable

namespace PatillaDash.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatillaDbContext))]
    [Migration("20260826204021_AgregarProductoActivo")]
    partial class AgregarProductoActivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PatillaDash.Domain.Entities.CompraInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuministroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("SuministroId");

                    b.ToTable("ComprasInsumo", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.ConsumoSuministroDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CantidadGastada")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistroVentaDiariaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuministroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegistroVentaDiariaId");

                    b.HasIndex("SuministroId");

                    b.ToTable("ConsumosSuministroDiario", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.DetalleVentaDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistroVentaDiariaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RegistroVentaDiariaId");

                    b.ToTable("DetallesVentaDiaria", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.InventarioLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuministroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SuministroId");

                    b.HasIndex("LocalId", "SuministroId")
                        .IsUnique();

                    b.ToTable("InventariosLocal", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locales", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.PagoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VendedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("VendedorId");

                    b.ToTable("PagosEmpleado", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.RegistroVentaDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalEfectivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTransferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VendedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("VendedorId");

                    b.ToTable("RegistrosVentaDiaria", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.Suministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimoAlerta")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suministros", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LocalId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.CompraInsumo", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PatillaDash.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Suministro");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.ConsumoSuministroDiario", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.RegistroVentaDiaria", "RegistroVentaDiaria")
                        .WithMany("Consumos")
                        .HasForeignKey("RegistroVentaDiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatillaDash.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistroVentaDiaria");

                    b.Navigation("Suministro");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.DetalleVentaDiaria", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PatillaDash.Domain.Entities.RegistroVentaDiaria", "RegistroVentaDiaria")
                        .WithMany("Detalles")
                        .HasForeignKey("RegistroVentaDiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("RegistroVentaDiaria");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.InventarioLocal", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.Local", "Local")
                        .WithMany("Inventarios")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PatillaDash.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Suministro");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.PagoEmpleado", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PatillaDash.Domain.Entities.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.RegistroVentaDiaria", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PatillaDash.Domain.Entities.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PatillaDash.Domain.Entities.Local", "Local")
                        .WithMany("Usuarios")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Local");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.Local", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PatillaDash.Domain.Entities.RegistroVentaDiaria", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
